### ISSUE TITLE
Page numbers for OED spec

### ISSUE THREAD

**Issue by sr-murthy** [Simplitium/OED#1]
I noticed that the OED spec PDF has no page numbers - this would be useful to have obviously, as you have a TOC referring to page numbers.

**Comment by aiste-kalinauskaite** [comment]
pdf has page numbers

**Comment by jonathanbethel** [comment]
![page_number](https://user-images.githubusercontent.com/29429041/47423546-2ebfb680-d77d-11e8-9bef-d9b6e635323c.png)

**Comment by sr-murthy** [comment]
Not in the version I had been working with, but perhaps you have an updated version. The footer gray colour makes this barely visible

![screen shot 2018-10-24 at 11 49 24](https://user-images.githubusercontent.com/9358070/47425702-13f04080-d783-11e8-9ec1-e61b2a4a3c03.png)

**Comment by jonathanbethel** [comment]
The most up to date version is hosted here on github
