### ISSUE TITLE
SQL signed integer data types for some integer columns

### ISSUE THREAD

**Issue by sr-murthy** [Simplitium/OED#3]
@jonathanbethel @jones-matt I note that there are some columns in the OED spec./schema with SQL data types given as `SmallInt`, `Int`, `BigInt`, but whose values will, in actual OED files, will almost certainly be non-negative and, in many cases, positive integers, for which unsigned integer data types are more appropriate. In the current OED spec. (v. 1.0.3) these columns are

	+-------------------+------------+----------+
	| column            | entity     | dtype    |
	|-------------------+------------+----------|
	| BIWaitingPeriod   | Loc        | smallint |
	| BuildingID        | Loc        | int      |
	| CondNumber        | Loc        | int      |
	| CondPriority      | Loc        | int      |
	| ConstructionCode  | Loc        | int      |
	| CorrelationGroup  | Loc        | int      |
	| DaysHeld          | Loc        | smallint |
	| HoursClause       | Acc        | int      |
	| LayerNumber       | Acc        | int      |
	| NumberOfBuildings | Loc        | int      |
	| NumberOfEmployees | Loc        | int      |
	| OccupancyCode     | Loc        | int      |
	| Payroll           | Loc        | int      |
	| ReinsLayerNumber  | ReinsInfo  | int      |
	| ReinsNumber       | ReinsScope | int      |
	| RoofYearBuilt     | Loc        | smallint |
	| YearBuilt         | Loc        | smallint |
	| YearUpgraded      | Loc        | smallint |
	+-------------------+------------+----------+

Is there a reason for this? I think SQL does define 8-, 16- and 32-bit unsigned integer data types, and many RDBMSs would support these. Would it be possible to update the spec. to fix this?

The context here is that of file validation - I can imagine a validation process or tool that would perform data type and range checks on the values in any given column (in an OED file) against the spec., for which the SQL data type for that column in the spec. would be a reference point.

**Comment by aiste-kalinauskaite** [comment]
MSSQL does not support unsigned smallint, int or bigint types. Checking whether any of the above columns contain values that are as specified (i.e. it includes being positive) is part of validation work. I am closing this comment, as it's not an issue.
