### ISSUE TITLE
Step policy terms

### ISSUE THREAD

**Issue by sr-murthy** [Simplitium/OED#4]
The changes listed in the recent 1.1.0 release include a mention of an addition of a new limit type value

>,6. Added LimitType = 3 (% of Limit) for step policies (i.e. PayOutType field).,,,

which isn't listed in the table of limit type values on page 26 of the OED PDF document.

https://github.com/Simplitium/OED/blob/master/Open%20Exposure%20Data.pdf

Is this an omission?

**Comment by sr-murthy** [comment]
In case anyone is looking at the issues page, I would draw your attention to the lack of description of the new columns introduced in OED 1.0.4 related to step policies (list below) - these are not described in any way in the PDF spec. even they seem to represent a new set of financial terms. This would be helpful.

Some of these, like `PayOutTypeField`, represent limit types, but there is no table in the PDF spec. describing the possible values (point raised above).

	PayoutBasis
	PayOutBuildingContentsEnd
	PayOutBuildingContentsStart
	PayOutBuildingEnd
	PayOutBuildingStart
	PayOutContentsEnd
	PayOutContentsStart
	PayOutLimitBuilding
	PayOutLimitBuildingContents
	PayOutLimitContents
	PayOutType

**Comment by aiste-kalinauskaite** [comment]
This will be updated in the new release

**Comment by sr-murthy** [comment]
Thanks
